version: '3.8'
services:
  db:
    image: postgres:15
    container_name: weather_postgres
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weather_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: weather_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - weather_network

  app:
    build: .
    container_name: weather_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/weather_db
    networks:
      - weather_network

volumes:
  postgres_data:

networks:
  weather_network:
    driver: bridge